### ISSUE TITLE
Minecraft runs in the backround and doesn't show up on taskbar or on command+tab on mac Bug report from,SmallMuffin#0328 (discord)

### ISSUE THREAD

**Issue by Rmni2** [CodeUtilities/CodeUtilities-2.0#151]
When I run fabric with CodeUtilities it doesn't show up it's like running on the background or something pressing command+tab won't show up either! here are some pictures!

<img width="1440" alt="Screen Shot 2022-03-04 at 22 23 01" src="https://user-images.githubusercontent.com/87783756/156836967-147f9963-46e7-4500-b490-d547abd6d969.png">
<img width="1433" alt="Screen Shot 2022-03-04 at 22 29 59" src="https://user-images.githubusercontent.com/87783756/156837129-9e0897d5-79ea-4562-81c4-4957a748c492.png">

**Comment by CheaterTim** [comment]
I know this is not on topic, but, how did you get over 1400 unread messages lmao
![image](https://user-images.githubusercontent.com/85891155/156841427-87d6df9a-90da-43a6-8d70-12a7e36187be.png)

**Comment by Rmni2** [comment]
> I know this is not on topic, but, how did you get over 1400 unread messages lmao ![image](https://user-images.githubusercontent.com/85891155/156841427-87d6df9a-90da-43a6-8d70-12a7e36187be.png)

I don't know that's a problem with my discord I don't know where the msgs are from
