### ISSUE TITLE
/heads Menu (bump kind of idk)

### ISSUE THREAD

**Issue by Electric131** [CodeUtilities/CodeUtilities-2.0#157]
(Possible bump/dupe idk?)
https://discord.com/channels/660239763479068713/840004170735681557/917470678247153664
(bumped idea ig?)

/heads does not work and doesn't even show in the /codeutilities menu

CodeUtilities Build:
802

Operating System:
Windows 11

Reproduction
1.) Get code utilities build 802
2.) Go to diamondfire and join a plot
3.) Type /heads and witness the results

Expected Result
Custom heads menu is shown

Actual Result
Normal DF head menu shown

Also I would like to ad, it doesn't even show up In the feature menu so idk whats up here.

**Comment by Reasonlesss** [comment]
/heads menu has been removed for a while now. This is intentional not a bug.

**Comment by Electric131** [comment]
> /heads menu has been removed for a while now. This is intentional not a bug.

I wish you would not close this so soon, because I would have added that it still shows up in settings then if this has been removed.
