### ISSUE TITLE
Seems to cause Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by james090500** [CodeUtilities/CodeUtilities-2.0#78]
Hi guys,

There seems to be a comparability issue with the [MinecraftCapes mod](https://minecraftcapes.net/) and maybe others.

Something your mod does seems to be causing handshake_failure when my mod request the users profile.

If you need any more info let me know.

[latest.log](https://github.com/CodeUtilities/CodeUtilities/files/7049529/latest.log)

**Comment by TechStreetDev** [comment]
1. Good job your mod seems really well made and a nice web GI
2. The reason i think this is happening is because developers & contributors of our mod get capes to reward them for their contributions.

I will look into this further tomorrow (if someone doesn't before me) to see if we can make a fix.

**Comment by james090500** [comment]
Thanks for the kind words. Let me know if I can be of any more help.

**Comment by TechStreetDev** [comment]
Hey again, could I ask what version of the mod your using because we cant seem to reproduce the issue.

**Comment by james090500** [comment]
Can't get the exact version right now. But 1.16.5 I just grabbed straight from your website. 

Using latest fabric API and fabric as well as the latest versions of my mod. 

If you need exact numbers I'll get them tomorrow when at my pc. 

Also just to confirm it's not limited to me. We had a few users in my discord with the same issue.

**Comment by tk2217** [comment]
Could you try this to with our [latest dev build](https://codeutilities-qy0oaqel3c6k.runkit.sh/3575596548/85933986) (mc 1.16.5). We resolved a few of the weird ssl issues, so hopefully that's fixed MinecraftCapes compatibility.

**Comment by james090500** [comment]
Sadly the same handshake errors. Also as promised:

Fabirc: fabric-loader-0.11.6-1.16.5

Mods:
CodeUtilities-2.2.2
fabric-api-0.39.2+1.16
MinecraftCapes+Fabric+1.16.5-11.0.1

[latest.log](https://github.com/CodeUtilities/CodeUtilities/files/7061706/latest.log)

**Comment by tk2217** [comment]
Could you try adding `-Djavax.net.debug=ssl:handshake:verbose` to your java parameters so we can hopefully pinpoint the exact issue. (`javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure` is infamously nondescript)

**Comment by james090500** [comment]
Hope this helps.

[latest.log](https://github.com/CodeUtilities/CodeUtilities/files/7062446/latest.log)

**Comment by tk2217** [comment]
I think we might have a working fix, but I'll leave this open until we can confirm. (Jars will be sent once github actions is done building them)

**Comment by tk2217** [comment]
Can you try [this jar](https://codeutilities-qy0oaqel3c6k.runkit.sh/3606908087/87059282) for the mod

**Comment by james090500** [comment]
Seems to be fixed, thanks for the help!

![2021-08-26_22 09 12](https://user-images.githubusercontent.com/20372645/131036366-9a1b0ffe-b28f-4d11-9210-5862d9ea921f.png)

**Comment by tk2217** [comment]
You're welcome! We've had some issues with ssl too and the bugged code was actually an effort to fix some of those. If you have any other compatibility issues with CodeUtilities I'm in the MinecraftCapes discord and you can contact us here.
