### ISSUE TITLE
Suggestion: CPU usage and TPS is displayed in f3 menu while on a plot

### ISSUE THREAD

**Issue by aflacc** [CodeUtilities/CodeUtilities-2.0#9]

**Comment by aflacc** [comment]
do it

**Comment by ryandev2** [comment]
it is impossible to get the cpu usage out of nowhere, you'd need something that the server tells the client how much cpu there is

**Comment by ryandev2** [comment]
oops but TPS is probably possible

**Comment by SirObby** [comment]
if its possible then do it

**Comment by ryandev2** [comment]
> if its possible then do it

CPU was already added (Uses /lagslayer)

**Comment by TechStreetDev** [comment]
> if its possible then do it

When is it coming?
When the devs get to it.
The devs are busy, they have a life and they decide when to add things as they please. Do not expect them to instantly add your cool suggestion.

**Comment by SirObby** [comment]
> > if its possible then do it
> 
> When is it coming?
> When the devs get to it.
> The devs are busy, they have a life and they decide when to add things as they please. Do not expect them to instantly add your cool suggestion.

its not my suggestion.

**Comment by Reasonlesss** [comment]
I'll take a look

**Comment by KabanFriends** [comment]
cpu usage is now displayed in the hud
tps is now displayed in the f3 screen
